# Generated by Django 3.2.5 on 2021-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210909_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logins',
            field=models.IntegerField(default=0),
        ),
    ]
