# Generated by Django 3.2.5 on 2021-10-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_logins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logins',
        ),
        migrations.AddField(
            model_name='profile',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
